### ISSUE TITLE
BetaBinomial

### ISSUE THREAD

**Issue by rezayas** [rezayas/StatisticalDistributionsLib#10]
I get these warnings for **BetaBinomial**: 

1>c:\users\ry87\box sync\codes\mycppresearchcodes\statisticaldistributionslib\statisticaldistributionslib\betabinomial.cpp(9): warning C4244: 'argument': conversion from 'const long double' to 'unsigned int', possible loss of data
1>c:\users\ry87\box sync\codes\mycppresearchcodes\statisticaldistributionslib\statisticaldistributionslib\betabinomial.cpp(20): warning C4244: 'argument': conversion from 'const long double' to 'long', possible loss of data

**Comment by NoLongerBreathedIn** [comment]
Tried to fix. Can't figure out the second one; don't worry about it.
