### ISSUE TITLE
Documentation for RNG.h

### ISSUE THREAD

**Issue by marcusrussi** [rezayas/StatisticalDistributionsLib#11]
Hi Eyal, I'm trying to use your RNG.h with one of the simulations I'm building. What I want to do is pull numeric values out of an RNG class I've already instantiated, and feed them into a bunch of new RNG classes which need to be seeded. I'm not very familiar with the StatisticalDistributionsLib or the STL RNG's you're using. Could you add comments to RNG.h to make it more obvious to me how to accomplish what I want, or explain to me what to call on an RNG object to get what I want? Thanks Marcus

**Comment by NoLongerBreathedIn** [comment]
RNG r(5234167895647L);
RNG s(r.mt_());
