### ISSUE TITLE
Distributions to implement

### ISSUE THREAD

**Issue by rezayas** [rezayas/StatisticalDistributionsLib#2]
Continuous distributions
   -    Uniform
   -    Exponential (and shifted)
   -    Normal
   -    LogNormal (and shifted)
   -    Gamma (and shifted)     Also take mean and StDev as parameters
   -    Weibull                 Also take mean and StDev as parameters
   -    Beta                    Also take mean and StDev as parameters
   -    Dirichlet
   -    Johnson Su      https://www.jmp.com/support/help/13/Continuous_Fit_Distributions.shtml
   -    Johnson Sb      https://www.jmp.com/support/help/13/Continuous_Fit_Distributions.shtml
   -    Johnson SI      https://www.jmp.com/support/help/13/Continuous_Fit_Distributions.shtml
   -    Triangular
   -    Chi

Discrete distributions
   -    Bernouli
   -    Empirical (categorical)
   -    Discrete uniform
   -    Poisson
   -    Binomial
   -    Multinomial
   -    Gamma-Poisson
   -    Beta-Binomial
   -    Negative Binomial

**Comment by NoLongerBreathedIn** [comment]
I can't do Weibull mean/stdev, because those are (a) complicated, and (b) require inverse gamma functions.

**Comment by NoLongerBreathedIn** [comment]
I can't do Dirichlet; that's a multidimensional distribution, and in the K=2 case it's just beta.

**Comment by NoLongerBreathedIn** [comment]
Multinomial is out too.

**Comment by rezayas** [comment]
Let's find a way to also implement multi-dimensional distributions. We need them!

**Comment by NoLongerBreathedIn** [comment]
That's done. Ideally, we could do Dirichlet-multinomial as well, but that's a bit tricky on the pdf front. On the simple generation front, it's a lot easier; just pick a random from Dirichlet and feed to multinomial.
