### ISSUE TITLE
Empirical

### ISSUE THREAD

**Issue by rezayas** [rezayas/StatisticalDistributionsLib#9]
I get these warnings for **empirical.cpp**: 

1>c:\users\ry87\box sync\codes\mycppresearchcodes\statisticaldistributionslib\statisticaldistributionslib\empirical.cpp(11): warning C4018: '<': signed/unsigned mismatch
1>c:\users\ry87\box sync\codes\mycppresearchcodes\statisticaldistributionslib\statisticaldistributionslib\empirical.cpp(13): warning C4018: '<': signed/unsigned mismatch
1>c:\users\ry87\box sync\codes\mycppresearchcodes\statisticaldistributionslib\statisticaldistributionslib\empirical.cpp(16): warning C4018: '<': signed/unsigned mismatch
1>c:\users\ry87\box sync\codes\mycppresearchcodes\statisticaldistributionslib\statisticaldistributionslib\empirical.cpp(20): warning C4018: '<': signed/unsigned mismatch
1>c:\users\ry87\box sync\codes\mycppresearchcodes\statisticaldistributionslib\statisticaldistributionslib\empirical.cpp(25): warning C4018: '>=': signed/unsigned mismatch
1>c:\users\ry87\box sync\codes\mycppresearchcodes\statisticaldistributionslib\statisticaldistributionslib\empirical.cpp(31): warning C4018: '<': signed/unsigned mismatch

**Comment by NoLongerBreathedIn** [comment]
Don't worry, these are stupid warnings. clang doesn't emit them. (I checked, and only some could conceivably cause problems, and even those aren't likely to, but I fixed them anyway.)
